// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACYuudGOkGmnN4TIL-kzucbzA5tuaM3ss',
    appId: '1:86009354317:web:615dd87009b2738933a404',
    messagingSenderId: '86009354317',
    projectId: 'groupie-771e9',
    authDomain: 'groupie-771e9.firebaseapp.com',
    databaseURL: 'https://groupie-771e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'groupie-771e9.appspot.com',
    measurementId: 'G-SYGQFEB6JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQGODGJMshw32xvLt1sB5tGMuiH0sqfj0',
    appId: '1:86009354317:android:74438180461b283933a404',
    messagingSenderId: '86009354317',
    projectId: 'groupie-771e9',
    databaseURL: 'https://groupie-771e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'groupie-771e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUsOtagXwxuXQRW8f5GLLefWU3BqpHi-g',
    appId: '1:86009354317:ios:37dda80ef3b9747333a404',
    messagingSenderId: '86009354317',
    projectId: 'groupie-771e9',
    databaseURL: 'https://groupie-771e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'groupie-771e9.appspot.com',
    iosBundleId: 'com.sheershbhatnagar.groupie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUsOtagXwxuXQRW8f5GLLefWU3BqpHi-g',
    appId: '1:86009354317:ios:a84256aeaee47cd833a404',
    messagingSenderId: '86009354317',
    projectId: 'groupie-771e9',
    databaseURL: 'https://groupie-771e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'groupie-771e9.appspot.com',
    iosBundleId: 'com.sheershbhatnagar.groupie.RunnerTests',
  );
}
